In [8]:
import numpy as np

arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,5,1,"hello"]
a

[1, 2, 3, 4, 5, 1, 'hello']

In [10]:
np.array(a)

array(['1', '2', '3', '4', '5', '1', 'hello'], dtype='<U21')

In [11]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(l)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [14]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [15]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
arr = np.linspace(1,10,6)
arr

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [18]:
#random generation function Normalization static
arr = np.random.rand(10)
arr

array([0.82763083, 0.86541885, 0.44675162, 0.7835285 , 0.61130719,
       0.32156465, 0.29488531, 0.26212264, 0.97342457, 0.40230129])

In [19]:
#random generation function Standardrization static
arr = np.random.randn(10)
arr

array([ 1.59566822, -1.68284235, -0.35601875, -0.41140629,  0.06842839,
        1.33259508, -0.11352959,  0.56442468,  0.38304899,  0.19481602])

In [20]:
#random interger generation 
arr = np.random.randint(10,20,10)
arr

array([18, 14, 18, 11, 15, 14, 12, 12, 18, 16], dtype=int32)

In [21]:
# ARRAY ATTRIBUTES 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape


(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

In [25]:
# ARRAY METHOD 
arr = np.array([[1,2,3],[4,0,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(0)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()


np.int64(40)

In [29]:
#column by sum indexing = 0
np.sum(arr,axis = 0)

array([12, 10, 18])

In [30]:
#Row by sum indexing = 1 
np.sum(arr,axis = 1)

array([ 6, 10, 24])

In [31]:
#finding middle element 
arr.mean()

np.float64(4.444444444444445)

In [32]:
#finding the maximum number index 
arr.argmax()

np.int64(8)

In [33]:
#finding the minimum number index 
arr.argmin()

np.int64(4)

In [34]:
Reshaping and resizing 

NameError: name 'Reshaping' is not defined

In [35]:
arr = np.arange (1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [38]:
arr = np.arange(1,31).reshape(6,5)
arr 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [39]:
slice = arr[3:,3:]
slice 

array([[19, 20],
       [24, 25],
       [29, 30]])

In [40]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
BOOLEAN INDEXING 

In [41]:
arr = np.arange(11,21)
arr 


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
bool_index = arr%2==0
bool_index 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arr = arr[bool_index]
arr 

array([12, 14, 16, 18, 20])