In [9]:
import numpy as np 

In [ ]:
ARRAY OPERATION 

ARITHEMATIC OPERATION

In [13]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1,a2 


(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [14]:
sum = a1 + a2 
sum 

array([ 7,  9, 11, 13, 15])

In [18]:
sub = a1-a2
sub2 = a2-a1
sub2 ,sub 


(array([5, 5, 5, 5, 5]), array([-5, -5, -5, -5, -5]))

In [19]:
mul = a1 * a2 
mul 

array([ 6, 14, 24, 36, 50])

In [20]:
div = a1/a2
div 

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [21]:
#flow division 

flow = a1//a2
flow 

array([0, 0, 0, 0, 0])

In [22]:
#Expotential 
expo = a1**a2
expo 

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
BROADCASTING 

In [24]:
l=[10,20,30,40]
arr = np.array(l)
arr ,l 

(array([10, 20, 30, 40]), [10, 20, 30, 40])

In [25]:
# sum 
arr +10

array([20, 30, 40, 50])

In [26]:
#subtraction 
arr -10

array([ 0, 10, 20, 30])

In [27]:
#multiplication 
arr * 2 

array([20, 40, 60, 80])

In [29]:
#division 
arr/10 

array([1., 2., 3., 4.])

In [30]:
# power 
arr ** 2 

array([ 100,  400,  900, 1600])

In [31]:
arr2 = np.arange(1,26).reshape(5,5)
arr2 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
# add 10 on whhole  number 
sum2 = arr2 + 10 
sum2 


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [36]:
#subtract 
sum2 - 10 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
#multiply 
mul2 = arr2 *2 
mul2 

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [40]:
#divide 
div2 = mul2 /2
div2  

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [41]:
#modlus 
mod = arr2 % 2 
mod 

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [ ]:
DEEP AND SHALLOW COPY

In [82]:
a = np.arange(1,21)
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [83]:
slice = a[:5]
slice = slice *10 
slice 

array([10, 20, 30, 40, 50])

In [84]:
a[4:6] *10 

array([50, 60])

In [85]:
a 
b=a.copy() 

In [86]:
a
b = a.copy()  

In [87]:
b[0] = 99 
b 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [88]:
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
MATRIX OPERATION 

In [102]:
A = np.array([[1,2],[4,5]]) 
B = np.array([[1,4],[2,5]])


In [103]:
A 

array([[1, 2],
       [4, 5]])

In [104]:
B 

array([[1, 4],
       [2, 5]])

In [106]:
A @ B  

array([[ 5, 14],
       [14, 41]])

In [107]:
np.dot(A,B) 

array([[ 5, 14],
       [14, 41]])

In [108]:
A.T 

array([[1, 4],
       [2, 5]])

In [111]:
B.T 

array([[1, 2],
       [4, 5]])

In [ ]:
'''ADVANCED ARRAY MANIPULATION 
1. STACKING ARRAY :- ADDING OF TWO ARRAY 
2. SPLITING ARRAY '''

In [112]:
A 

array([[1, 2],
       [4, 5]])

In [113]:
B 

array([[1, 4],
       [2, 5]])

In [115]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [116]:
#verticle stack

np.stack((a,b)) 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
#horizontaly 
np.hstack((a,b)) 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [118]:
#column stack
np.column_stack((a,b)) 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
SPLITING ARRAY 

In [124]:
c = np.arange(16).reshape(4,4)


In [128]:
c 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [129]:
np.hsplit(c,2)  

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [130]:
np.hsplit(c,4) 

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [131]:
np.vsplit(c,2) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [133]:
a= np.vsplit(c,4) 

In [135]:
for i in a:
    print(i) 

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
