In [5]:
import numpy as np 

In [ ]:
Numpy indexing and slicing of vector 

In [10]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
#find element by index no 
arr[9]

np.int64(20)

In [14]:
#slicing
arr[1:5]

array([12, 13, 14, 15])

In [15]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr[:4]

array([11, 12, 13, 14])

In [17]:
#slicing steps

arr[3::2]

array([14, 16, 18, 20])

In [ ]:
NUMPY INDEXING AND SLICING OF  MATRIX

In [18]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [20]:
#for printing rows
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
#for printing element in given matrix

arr[1,2]

np.int64(8)

In [23]:
#for printing more the one element 
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [25]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [26]:
slice = arr[1:,2:]
slice

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30]])

In [27]:
# for column print 

slice = arr[:,2]
slice

array([ 3,  8, 13, 18, 23, 28])

In [ ]:
BOOLEAN INDEXING 

In [6]:
arr = np.arange(11,21)
arr 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
bool_index = arr %2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr